name: Linter

on:
  push:
    branches:    
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  eslint:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-npm.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  sonarcloud:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if needed)
        run: npm ci

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=vilteros-api
            -Dsonar.organization=vvalembois
            -Dsonar.coverage.exclusions=**/*
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}