name: Build Docker Image

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          echo "Git tag: $GITHUB_REF"
          # Extract the tag name from the ref (refs/tags/v1.0 → v1.0)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker build . --file Dockerfile --tag vilteros-api:$TAG_NAME